---
name: "Deliver / Container / Bash Test"

concurrency:
  group: "deliver-docker-bash-test"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deliver-docker-bash-test-l0:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "BASH_TEST_L0_REDHAT"
          - "BASH_TEST_L0_FEDORA"
          - "BASH_TEST_L0_DEBIAN"
          - "BASH_TEST_L0_UBUNTU"
          - "BASH_TEST_L0_OTHER"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-base"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-project ${{ matrix.scope }} ON"

  deliver-docker-bash-test-l1:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "BASH_TEST_L1"

    needs:
      - "deliver-docker-bash-test-l0"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-base"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-project ${{ matrix.scope }} ON"

  deliver-docker-bash-test-l2:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "BASH_TEST_L2"

    needs:
      - "deliver-docker-bash-test-l1"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-base"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-project ${{ matrix.scope }} ON"

  deliver-docker-bash-test-l3:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "BASH_TEST_L3"

    needs:
      - "deliver-docker-bash-test-l2"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-base"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-project ${{ matrix.scope }} ON"
...
